name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main  # Replace with your target branch if it's not main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js (v18)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: |
        npm run build
        ls -al dist  # Debug: List files in the 'dist' directory to verify its creation

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      run: |
        if [ ! -d "dist" ]; then
          echo "Build directory not found. Exiting deployment.";
          exit 1;
        fi
        netlify deploy --dir=dist --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}
